ALTER TABLE formula_reference DROP CONSTRAINT "FK_FORMULA_REFERENCES_FORMULA_ID";
ALTER TABLE formula_reference ADD CONSTRAINT "FK_FORMULA_REFERENCE_FORMULA_ID" FOREIGN KEY (formula_id) REFERENCES formula (id) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE algebra_formula DROP CONSTRAINT "FK_ALGEBRA_FORMULA_FORMULA_ID";
ALTER TABLE algebra_formula DROP CONSTRAINT "FK_ALGEBRA_FORMULA_ALGEBRA_ID";
ALTER TABLE algebra_formula ADD CONSTRAINT "FK_ALGEBRA_FORMULA_FORMULA_ID" FOREIGN KEY (formula_id) REFERENCES formula (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE algebra_formula ADD CONSTRAINT "FK_ALGEBRA_FORMULA_ALGEBRA_ID" FOREIGN KEY (algebra_id) REFERENCES algebra (id) ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE proof_formula_used DROP CONSTRAINT "FK_PROVE_PROVE_ID";
ALTER TABLE proof_formula_used DROP CONSTRAINT "FK_PROVE_FORMULA_ID";
ALTER TABLE proof_formula_used ADD CONSTRAINT "FK_PROOF_FORMULA_USED_PROOF_ID" FOREIGN KEY (proof_id) REFERENCES proof (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE proof_formula_used ADD CONSTRAINT "FK_PROOF_FORMULA_USED_FORMULA_ID" FOREIGN KEY (formula_id) REFERENCES formula (id) ON UPDATE NO ACTION ON DELETE CASCADE;

-- Proof Formula Proves
ALTER TABLE proof_formula_proves DROP CONSTRAINT "FK_PROOF_FORMULA_PROVE_ID";
ALTER TABLE proof_formula_proves DROP CONSTRAINT "FK_PROOF_FORMULA_FORMULA";
ALTER TABLE proof_formula_proves ADD CONSTRAINT "FK_PROOF_FORMULA_PROVES_FORMULA_ID" FOREIGN KEY (formula_id) REFERENCES formula (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE proof_formula_proves ADD CONSTRAINT "FK_PROOF_FORMULA_PROVES_PROOF_ID" FOREIGN KEY (proof_id) REFERENCES proof (id) ON UPDATE NO ACTION ON DELETE CASCADE;

-- Queuejob_formulas
ALTER TABLE queuejob_formulas ADD CONSTRAINT "FK_QUEUEJOB_FORMULA_FORMULA_ID" FOREIGN KEY (formula_id) REFERENCES formula (id) ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE queuejob_formulas ADD CONSTRAINT "FK_QUEUEJOB_FORMULAS_QUEUEJOB_ID" FOREIGN KEY (queuejob_id) REFERENCES queuejob (id) ON UPDATE NO ACTION ON DELETE CASCADE;

-- Tabelle: atp_option
ALTER TABLE atp_option ADD CONSTRAINT "FK_ATP_OPTION_ATP_ID" FOREIGN KEY (atp_id) REFERENCES atp (id) ON UPDATE NO ACTION ON DELETE CASCADE;
