ALTER TABLE proof_formula_proves DROP CONSTRAINT "FK_PROOF_FORMULA_FORMULA";
ALTER TABLE proof_formula_proves DROP CONSTRAINT "PK_PROOF_FORMULA_PROVES";
ALTER TABLE proof_formula_proves ADD CONSTRAINT "FK_PROOF_FORMULA_PROVES_PROOF_ID" FOREIGN KEY (proof_id) REFERENCES proof (id) ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE proof_formula_used ADD CONSTRAINT "FK_PROOF_FORMULA_USED_PROOF_ID" FOREIGN KEY (proof_id) REFERENCES proof (id) ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE proof_step ADD CONSTRAINT "FK_PROOF_STEP_PROOF_ID" FOREIGN KEY (proof_id) REFERENCES proof (id) ON UPDATE NO ACTION ON DELETE CASCADE;
